Repository tripledes/thesheriff, pull requests merged in 2019-12, with the labels that each got.

#30 fix(28): change relationship for miembros
  thesheriff/infrastructure/asalto/asalto_mysql_repository.py
Labels: bug

#35 feature: create BandidoMySQLRepository
  doc/build/doctrees/environment.pickle
  doc/build/doctrees/index.doctree
  doc/build/html/_sources/index.rst.txt
  doc/build/html/genindex.html
  doc/build/html/index.html
  doc/build/html/objects.inv
  doc/build/html/py-modindex.html
  doc/build/html/searchindex.js
  doc/source/index.rst
  thesheriff/domain/bandido/__init__.py
  thesheriff/domain/bandido/bandido_repository.py
  thesheriff/infrastructure/__init__.py
  thesheriff/infrastructure/bandido/__init__.py
  thesheriff/infrastructure/bandido/bandido_mysql_repository.py
Labels: enhancement

#33 fix(32): AsaltoMySQLRespotiry to match interface
  doc/build/doctrees/environment.pickle
  doc/build/doctrees/index.doctree
  doc/build/html/genindex.html
  doc/build/html/index.html
  doc/build/html/objects.inv
  doc/build/html/searchindex.js
  thesheriff/__init__.py
  thesheriff/domain/asalto/asalto_repository.py
  thesheriff/infrastructure/asalto/asalto_mysql_repository.py
Labels: bug

#38 [BandaRepository] - MySQL implementation
  doc/build/html/_sources/index.rst.txt
  doc/build/html/index.html
  thesheriff/domain/banda/banda_repository.py
  thesheriff/infrastructure/banda/__init__.py
  thesheriff/infrastructure/banda/banda_mysql_repository.py
Labels: enhancement

#41 feature(23): Crear Blueprint para Asaltos
  Pipfile
  Pipfile.lock
  thesheriff/application.py
  thesheriff/application/__init__.py
  thesheriff/application/bandido/__init__.py
  thesheriff/application/bandido/puntuar_asalto.py
  thesheriff/configuration.py
  thesheriff/domain/bandido/puntuacion.py
  thesheriff/infrastructure/asalto/__init__.py
  thesheriff/infrastructure/asalto/asalto_controller.py
Labels: enhancement

#39 Feature: Crear bandido
  tests/asalto_mock_repository.py
  tests/bandido_mock_repository.py
  tests/test_calificar_asalto.py
  tests/test_crear_bandido.py
  tests/test_puntuar_asalto.py
  thesheriff/application/bandido/crear_bandido.py
  thesheriff/application/bandido/puntuar_asalto.py
  thesheriff/domain/bandido/bandido.py
  thesheriff/domain/bandido/bandido_factory.py
Labels: enhancement

#47 A lot of minor issues fixed
  tests/test_calificar_asalto.py
  tests/test_crear_bandido.py
  tests/test_puntuar_asalto.py
  thesheriff/application/asalto/calificar_asalto.py
  thesheriff/application/bandido/crear_banda.py
  thesheriff/application/bandido/crear_bandido.py
  thesheriff/application/bandido/puntuar_asalto.py
  thesheriff/application/bandido/unirse_a_banda.py
  thesheriff/configuration.py
  thesheriff/domain/asalto/asalto.py
  thesheriff/domain/asalto/asalto_factory.py
  thesheriff/domain/asalto/asalto_repository.py
  thesheriff/domain/banda/banda.py
  thesheriff/domain/banda/banda_factory.py
  thesheriff/domain/banda/banda_repository.py
  thesheriff/domain/bandido/bandido.py
  thesheriff/domain/bandido/puntuacion.py
  thesheriff/domain/bandido/sheriff.py
Labels: bug, test

#52 Issue #45 - listar_amigos done (TBChecked)
  thesheriff/application/bandido/listar_amigos.py
  thesheriff/domain/bandido/bandido.py
  thesheriff/domain/bandido/repository/bandido_repository.py
  thesheriff/infrastructure/controllers/bandido_controller.py
  thesheriff/infrastructure/repositoy/mysql_bandido_repository.py
Labels: enhancement

#54 [Issue #17] - Listar bandas de un bandido
  tests/banda_mock_repository.py
  tests/bandido_mock_repository.py
  tests/test_listar_amigos.py
  tests/test_listar_bandas.py
  thesheriff/app.py
  thesheriff/application/bandido/crear_banda.py
  thesheriff/application/bandido/listar_amigos.py
  thesheriff/application/bandido/listar_bandas.py
  thesheriff/domain/banda/banda.py
  thesheriff/domain/bandido/bandido.py
  thesheriff/domain/bandido/repository/bandido_repository.py
  thesheriff/infrastructure/controllers/bandido_controller.py
  thesheriff/infrastructure/repositoy/mysql_banda_repository.py
  thesheriff/infrastructure/repositoy/mysql_bandido_repository.py
Labels: enhancement, test

#60 Minor things + Bandido bluePrint
  tests/test_crear_bandido.py
  tests/test_puntuar_asalto.py
  thesheriff/application/asalto/calificar_asalto.py
  thesheriff/application/bandido/crear_banda.py
  thesheriff/application/bandido/crear_bandido.py
  thesheriff/application/bandido/listar_amigos.py
  thesheriff/application/bandido/listar_bandas.py
  thesheriff/application/bandido/request/__init__.py
  thesheriff/application/bandido/request/crear_bandido_request.py
  thesheriff/application/bandido/unirse_a_banda.py
  thesheriff/configuration.py
  thesheriff/domain/asalto/asalto.py
  thesheriff/domain/bandido/bandido.py
  thesheriff/domain/bandido/sheriff.py
  thesheriff/infrastructure/controllers/bandido_controller.py
Labels: bug, enhancement

#61 #48 Actions to be performed through Banda - From app point of view
  tests/banda_mock_repository.py
  thesheriff/app.py
  thesheriff/application/banda/request/__init__.py
  thesheriff/application/banda/request/unirse_a_banda_request.py
  thesheriff/application/bandido/crear_banda.py
  thesheriff/application/bandido/unirse_a_banda.py
  thesheriff/domain/banda/banda.py
  thesheriff/domain/banda/banda_factory.py
  thesheriff/infrastructure/controllers/banda_controller.py
Labels: enhancement

#63 fix(tests): tests back to green
  tests/mock_gang_repository.py
  tests/mock_outlaw_repository.py
  tests/test_grade_raid.py
  tests/test_rate_raid.py
  thesheriff/domain/outlaw/outlaw.py
  thesheriff/domain/outlaw/outlaw_factory.py
  thesheriff/domain/outlaw/sheriff.py
Labels: bug, test

#66 README.md minor fixes
  README.md
Labels: bug

#67 [Issue #25] Fin de asalto
  tests/test_end_raid.py
  thesheriff/application/raid/end_raid.py
  thesheriff/domain/raid/raid.py
Labels: enhancement

#68 usecase: fixed create_outlaw use case
  .travis.yml
  Makefile
  README.md
  examples/json/create_outlaw.json
  thesheriff/app.py
  thesheriff/application/outlaw/list_friends.py
  thesheriff/application/outlaw/rate_raid.py
  thesheriff/application/raid/grade_raid.py
  thesheriff/configuration.py
  thesheriff/domain/outlaw/__init__.py
  thesheriff/domain/raid/__init__.py
  thesheriff/domain/raid/raid_factory.py
  thesheriff/infrastructure/__init__.py
  thesheriff/infrastructure/controllers/gang_controller.py
  thesheriff/infrastructure/controllers/outlaw_controller.py
  thesheriff/infrastructure/controllers/raid_controller.py
  thesheriff/infrastructure/repository/.gitignore
  thesheriff/infrastructure/repository/__init__.py
  thesheriff/infrastructure/repository/mysql_gang_repository.py
  thesheriff/infrastructure/repository/mysql_outlaw_repository.py
  thesheriff/infrastructure/repository/mysql_raid_repository.py
Labels: bug

#71 fix: ci green again
  thesheriff/application/raid/end_raid.py
Labels: bug

#73 Rate raid from outlaw
  tests/test_end_raid.py
  tests/test_grade_raid.py
  tests/test_rate_raid.py
  thesheriff/domain/outlaw/score.py
  thesheriff/domain/raid/raid.py
  thesheriff/domain/raid/raid_factory.py
  thesheriff/domain/raid/repository/raid_repository.py
  thesheriff/infrastructure/controllers/outlaw_controller.py
  thesheriff/infrastructure/controllers/raid_controller.py
  thesheriff/infrastructure/repository/mysql_raid_repository.py
Labels: bug, enhancement, test

#75 Outlaw minor fixes
  thesheriff/domain/outlaw/outlaw.py
Labels: bug

#76 feature: add readthedocs integration
  .readthedocs.yml
  doc/build/doctrees/contents.doctree
  doc/build/doctrees/environment.pickle
  doc/build/doctrees/infrastructure.doctree
  doc/build/html/_sources/contents.rst.txt
  doc/build/html/contents.html
  doc/build/html/genindex.html
  doc/build/html/infrastructure.html
  doc/build/html/objects.inv
  doc/build/html/py-modindex.html
  doc/build/html/search.html
  doc/build/html/searchindex.js
  doc/build/html/usage.html
  doc/requirements.txt
  doc/source/conf.py
  doc/source/contents.rst
Labels: documentation, enhancement

#79 doc: add application package documentation
  doc/build/doctrees/application.doctree
  doc/build/doctrees/environment.pickle
  doc/build/doctrees/index.doctree
  doc/build/html/_sources/application.rst.txt
  doc/build/html/_sources/index.rst.txt
  doc/build/html/application.html
  doc/build/html/domain.html
  doc/build/html/genindex.html
  doc/build/html/index.html
  doc/build/html/infrastructure.html
  doc/build/html/objects.inv
  doc/build/html/py-modindex.html
  doc/build/html/search.html
  doc/build/html/searchindex.js
  doc/build/html/usage.html
  doc/source/application.rst
  doc/source/index.rst
  thesheriff/application/gang/request/join_gang_request.py
  thesheriff/application/outlaw/create_gang.py
  thesheriff/application/outlaw/create_outlaw.py
  thesheriff/application/outlaw/join_gang.py
  thesheriff/application/outlaw/list_friends.py
  thesheriff/application/outlaw/list_gangs.py
  thesheriff/application/outlaw/rate_raid.py
  thesheriff/application/outlaw/request/create_outlaw_request.py
  thesheriff/application/raid/end_raid.py
  thesheriff/application/raid/grade_raid.py
Labels: documentation, enhancement

#85 feature: Gang List Gangs
  doc/build/doctrees/application.doctree
  doc/build/doctrees/environment.pickle
  doc/build/doctrees/infrastructure.doctree
  doc/build/html/_sources/application.rst.txt
  doc/build/html/application.html
  doc/build/html/genindex.html
  doc/build/html/infrastructure.html
  doc/build/html/objects.inv
  doc/build/html/py-modindex.html
  doc/build/html/searchindex.js
  doc/source/application.rst
  tests/test_gang_list_gangs.py
  tests/test_outlaw_list_gangs.py
  thesheriff/application/gang/list_gangs.py
  thesheriff/infrastructure/controllers/gang_controller.py
Labels: enhancement

#88 CreateRaid connected from controller
  doc/build/doctrees/application.doctree
  doc/build/doctrees/domain.doctree
  doc/build/doctrees/environment.pickle
  doc/build/doctrees/index.doctree
  doc/build/doctrees/infrastructure.doctree
  doc/build/doctrees/usage.doctree
  doc/build/html/application.html
  doc/build/html/domain.html
  doc/build/html/infrastructure.html
  doc/build/html/searchindex.js
  examples/json/create_raid.json
  examples/json/rate_raid.json
  thesheriff/infrastructure/controllers/outlaw_controller.py
  thesheriff/infrastructure/controllers/raid_controller.py
Labels: enhancement

#90 fix: validated list all gangs use case
  doc/build/doctrees/application.doctree
  doc/build/doctrees/domain.doctree
  doc/build/doctrees/environment.pickle
  doc/build/doctrees/index.doctree
  doc/build/doctrees/infrastructure.doctree
  doc/build/doctrees/usage.doctree
  doc/build/html/_sources/usage.rst.txt
  doc/build/html/domain.html
  doc/build/html/infrastructure.html
  doc/build/html/searchindex.js
  doc/build/html/usage.html
  doc/source/usage.rst
  thesheriff/application/gang/list_gangs.py
  thesheriff/application/raid/create_raid.py
  thesheriff/domain/gang/gang.py
  thesheriff/domain/gang/gang_factory.py
  thesheriff/infrastructure/controllers/gang_controller.py
  thesheriff/infrastructure/repository/mysql_gang_repository.py
Labels: bug

#91 fix: add doc on new use cases
  doc/build/doctrees/application.doctree
  doc/build/doctrees/environment.pickle
  doc/build/html/_sources/application.rst.txt
  doc/build/html/application.html
  doc/build/html/genindex.html
  doc/build/html/objects.inv
  doc/build/html/py-modindex.html
  doc/build/html/searchindex.js
  doc/source/application.rst
  tests/test_create_raid.py
  thesheriff/application/raid/create_raid.py
  thesheriff/application/raid/create_raid_request.py
  thesheriff/application/raid/request/create_raid_request.py
  thesheriff/infrastructure/controllers/raid_controller.py
Labels: documentation, enhancement

#95 Potpourri of tiny things
  doc/build/doctrees/application.doctree
  doc/build/doctrees/domain.doctree
  doc/build/doctrees/environment.pickle
  doc/build/doctrees/index.doctree
  doc/build/doctrees/infrastructure.doctree
  doc/build/doctrees/usage.doctree
  doc/build/html/application.html
  doc/build/html/infrastructure.html
  doc/build/html/searchindex.js
  examples/json/invite_friend.json
  examples/json/join_gang.json
  thesheriff/infrastructure/controllers/gang_controller.py
  thesheriff/infrastructure/controllers/outlaw_controller.py
Labels: bug, documentation

#97 fix: validate create raid use case
  Makefile
  doc/build/doctrees/application.doctree
  doc/build/doctrees/domain.doctree
  doc/build/doctrees/environment.pickle
  doc/build/doctrees/index.doctree
  doc/build/doctrees/infrastructure.doctree
  doc/build/doctrees/usage.doctree
  doc/build/html/_sources/usage.rst.txt
  doc/build/html/domain.html
  doc/build/html/genindex.html
  doc/build/html/infrastructure.html
  doc/build/html/objects.inv
  doc/build/html/searchindex.js
  doc/build/html/usage.html
  doc/source/usage.rst
  examples/json/create_raid.json
  tests/mocks/mock_gang_repository.py
  tests/mocks/mock_outlaw_repository.py
  tests/mocks/mock_raid_repository.py
  tests/test_create_gang.py
  tests/test_create_outlaw.py
  tests/test_create_raid.py
  tests/test_end_raid.py
  tests/test_grade_raid.py
  tests/test_rate_raid.py
  thesheriff/application/raid/create_raid.py
  thesheriff/application/raid/end_raid.py
  thesheriff/domain/gang/gang.py
  thesheriff/domain/gang/gang_factory.py
  thesheriff/domain/outlaw/outlaw.py
  thesheriff/domain/outlaw/outlaw_factory.py
  thesheriff/domain/outlaw/sheriff.py
  thesheriff/domain/raid/raid.py
  thesheriff/domain/raid/raid_factory.py
  thesheriff/infrastructure/controllers/raid_controller.py
  thesheriff/infrastructure/repository/mysql_gang_repository.py
  thesheriff/infrastructure/repository/mysql_outlaw_repository.py
  thesheriff/infrastructure/repository/mysql_raid_repository.py
Labels: CU behavioral validation, bug

#100 minor fixes for docs and code
  Makefile
  doc/build/doctrees/application.doctree
  doc/build/doctrees/domain.doctree
  doc/build/doctrees/environment.pickle
  doc/build/doctrees/infrastructure.doctree
  doc/build/html/_sources/application.rst.txt
  doc/build/html/_sources/domain.rst.txt
  doc/build/html/_sources/infrastructure.rst.txt
  doc/build/html/application.html
  doc/build/html/domain.html
  doc/build/html/genindex.html
  doc/build/html/index.html
  doc/build/html/infrastructure.html
  doc/build/html/objects.inv
  doc/build/html/py-modindex.html
  doc/build/html/searchindex.js
  doc/source/application.rst
  doc/source/domain.rst
  doc/source/infrastructure.rst
  tests/test_end_raid.py
  thesheriff/application/outlaw/create_gang.py
  thesheriff/application/outlaw/create_outlaw.py
  thesheriff/application/outlaw/invite_friend.py
  thesheriff/application/outlaw/join_gang.py
  thesheriff/application/outlaw/list_friends.py
  thesheriff/application/outlaw/list_gangs.py
  thesheriff/application/raid/create_raid.py
  thesheriff/application/raid/end_raid.py
  thesheriff/application/raid/grade_raid.py
  thesheriff/application/raid/request/end_raid_request.py
  thesheriff/configuration.py
  thesheriff/domain/gang/gang.py
  thesheriff/domain/gang/repository/gang_repository.py
  thesheriff/domain/mail/mail.py
  thesheriff/domain/mail/notifier/mail_notifier.py
  thesheriff/domain/outlaw/outlaw.py
  thesheriff/domain/outlaw/outlaw_factory.py
  thesheriff/domain/outlaw/repository/outlaw_repository.py
  thesheriff/domain/outlaw/score.py
  thesheriff/domain/outlaw/sheriff.py
  thesheriff/domain/raid/raid.py
  thesheriff/domain/raid/repository/raid_repository.py
  thesheriff/infrastructure/controllers/gang_controller.py
  thesheriff/infrastructure/controllers/outlaw_controller.py
  thesheriff/infrastructure/controllers/raid_controller.py
  thesheriff/infrastructure/notifier/__init__.py
  thesheriff/infrastructure/notifier/smtp_mail_notifier.py
  thesheriff/infrastructure/repository/mysql_gang_repository.py
  thesheriff/infrastructure/repository/mysql_outlaw_repository.py
  thesheriff/infrastructure/repository/mysql_raid_repository.py
Labels: documentation, enhancement

#101 refactor: unify controller responses
  doc/build/doctrees/application.doctree
  doc/build/doctrees/environment.pickle
  doc/build/doctrees/infrastructure.doctree
  doc/build/html/application.html
  doc/build/html/infrastructure.html
  doc/build/html/searchindex.js
  thesheriff/infrastructure/controllers/gang_controller.py
  thesheriff/infrastructure/controllers/outlaw_controller.py
  thesheriff/infrastructure/controllers/raid_controller.py
Labels: documentation

#105 Diagrams
  doc/diagrams/the_sheriff_class_diagram.png
  doc/diagrams/thesheriff_use-case_diagram.png
Labels: documentation

#103 Feature/documentation introduction
  Pipfile
  doc/build/doctrees/application.doctree
  doc/build/doctrees/domain.doctree
  doc/build/doctrees/environment.pickle
  doc/build/doctrees/index.doctree
  doc/build/doctrees/infrastructure.doctree
  doc/build/doctrees/introduction.doctree
  doc/build/doctrees/usage.doctree
  doc/build/html/_sources/index.rst.txt
  doc/build/html/_sources/introduction.rst.txt
  doc/build/html/_static/basic.css
  doc/build/html/_static/documentation_options.js
  doc/build/html/_static/searchtools.js
  doc/build/html/application.html
  doc/build/html/domain.html
  doc/build/html/genindex.html
  doc/build/html/index.html
  doc/build/html/infrastructure.html
  doc/build/html/introduction.html
  doc/build/html/objects.inv
  doc/build/html/py-modindex.html
  doc/build/html/search.html
  doc/build/html/searchindex.js
  doc/build/html/usage.html
  doc/source/index.rst
  doc/source/introduction.rst
Labels: documentation

#109 ListAllGangs in a separated endpoint
  doc/build/doctrees/application.doctree
  doc/build/doctrees/domain.doctree
  doc/build/doctrees/environment.pickle
  doc/build/doctrees/index.doctree
  doc/build/doctrees/infrastructure.doctree
  doc/build/doctrees/introduction.doctree
  doc/build/doctrees/usage.doctree
  doc/build/html/_sources/usage.rst.txt
  doc/build/html/_static/basic.css
  doc/build/html/_static/documentation_options.js
  doc/build/html/_static/searchtools.js
  doc/build/html/application.html
  doc/build/html/domain.html
  doc/build/html/genindex.html
  doc/build/html/index.html
  doc/build/html/infrastructure.html
  doc/build/html/introduction.html
  doc/build/html/objects.inv
  doc/build/html/py-modindex.html
  doc/build/html/search.html
  doc/build/html/searchindex.js
  doc/build/html/usage.html
  doc/source/usage.rst
  thesheriff/infrastructure/controllers/gang_controller.py
Labels: refactor

#110 Documentaltion: Tools finished
  doc/build/doctrees/application.doctree
  doc/build/doctrees/environment.pickle
  doc/build/doctrees/index.doctree
  doc/build/doctrees/infrastructure.doctree
  doc/build/doctrees/introduction.doctree
  doc/build/doctrees/tools.doctree
  doc/build/doctrees/usage.doctree
  doc/build/html/_images/Docker.png
  doc/build/html/_images/the_sheriff_class_diagram.png
  doc/build/html/_images/the_sheriff_class_diagram_zoom_contracts.png
  doc/build/html/_sources/index.rst.txt
  doc/build/html/_sources/introduction.rst.txt
  doc/build/html/_sources/tools.rst.txt
  doc/build/html/_static/basic.css
  doc/build/html/_static/documentation_options.js
  doc/build/html/_static/searchtools.js
  doc/build/html/application.html
  doc/build/html/genindex.html
  doc/build/html/index.html
  doc/build/html/infrastructure.html
  doc/build/html/introduction.html
  doc/build/html/objects.inv
  doc/build/html/py-modindex.html
  doc/build/html/search.html
  doc/build/html/searchindex.js
  doc/build/html/tools.html
  doc/build/html/usage.html
  doc/images/Docker.png
  doc/images/the_sheriff_class_diagram.png
  doc/images/the_sheriff_class_diagram_zoom_contracts.png
  doc/source/index.rst
  doc/source/introduction.rst
  doc/source/tools.rst
Labels: documentation

#111 Sheriff created by Factory & docs updated
  doc/build/doctrees/application.doctree
  doc/build/doctrees/domain.doctree
  doc/build/doctrees/environment.pickle
  doc/build/doctrees/index.doctree
  doc/build/doctrees/infrastructure.doctree
  doc/build/doctrees/introduction.doctree
  doc/build/doctrees/tools.doctree
  doc/build/doctrees/usage.doctree
  doc/build/html/_static/basic.css
  doc/build/html/_static/documentation_options.js
  doc/build/html/_static/searchtools.js
  doc/build/html/application.html
  doc/build/html/domain.html
  doc/build/html/genindex.html
  doc/build/html/index.html
  doc/build/html/infrastructure.html
  doc/build/html/introduction.html
  doc/build/html/objects.inv
  doc/build/html/py-modindex.html
  doc/build/html/search.html
  doc/build/html/searchindex.js
  doc/build/html/tools.html
  doc/build/html/usage.html
  thesheriff/application/raid/create_raid.py
  thesheriff/domain/outlaw/outlaw_factory.py
  thesheriff/domain/outlaw/sheriff_factory.py
Labels: question, refactor

#112 Class diagram enhanced
  doc/diagrams/the_sheriff_class_diagram.png
  doc/diagrams/thesheriff_class_diagram.png
Labels: documentation

#104 validated rate raid use case
  doc/build/doctrees/application.doctree
  doc/build/doctrees/domain.doctree
  doc/build/doctrees/environment.pickle
  doc/build/doctrees/index.doctree
  doc/build/doctrees/infrastructure.doctree
  doc/build/doctrees/introduction.doctree
  doc/build/doctrees/tools.doctree
  doc/build/doctrees/usage.doctree
  doc/build/html/_sources/introduction.rst.txt
  doc/build/html/_sources/tools.rst.txt
  doc/build/html/application.html
  doc/build/html/domain.html
  doc/build/html/genindex.html
  doc/build/html/infrastructure.html
  doc/build/html/introduction.html
  doc/build/html/objects.inv
  doc/build/html/searchindex.js
  doc/build/html/tools.html
  doc/source/introduction.rst
  doc/source/tools.rst
  examples/json/create_raid.json
  examples/json/rate_raid.json
  tests/mocks/mock_raid_repository.py
  tests/test_end_raid.py
  tests/test_grade_raid.py
  tests/test_rate_raid.py
  thesheriff/application/outlaw/list_friends.py
  thesheriff/application/outlaw/rate_raid.py
  thesheriff/application/raid/create_raid.py
  thesheriff/application/raid/grade_raid.py
  thesheriff/application/raid/request/create_raid_request.py
  thesheriff/configuration.py
  thesheriff/domain/gang/gang.py
  thesheriff/domain/gang/gang_factory.py
  thesheriff/domain/gang/repository/gang_repository.py
  thesheriff/domain/outlaw/outlaw.py
  thesheriff/domain/outlaw/outlaw_factory.py
  thesheriff/domain/outlaw/sheriff.py
  thesheriff/domain/raid/raid.py
  thesheriff/domain/raid/raid_factory.py
  thesheriff/domain/raid/repository/raid_repository.py
  thesheriff/infrastructure/controllers/raid_controller.py
  thesheriff/infrastructure/repository/mysql_gang_repository.py
  thesheriff/infrastructure/repository/mysql_raid_repository.py
Labels: CU behavioral validation

#114 fix: rate raid after last PR
  doc/build/doctrees/application.doctree
  doc/build/doctrees/domain.doctree
  doc/build/doctrees/environment.pickle
  doc/build/html/application.html
  doc/build/html/domain.html
  doc/build/html/searchindex.js
  thesheriff/application/raid/grade_raid.py
  thesheriff/application/raid/request/create_raid_request.py
  thesheriff/domain/raid/raid.py
  thesheriff/domain/raid/raid_factory.py
  thesheriff/infrastructure/repository/mysql_raid_repository.py
Labels: bug

#113 Updated class diagram with MailFactory
  doc/diagrams/thesheriff_class_diagram.png
Labels: documentation

#102 add use cases grad_raid and end_raid to controller
  doc/build/doctrees/application.doctree
  doc/build/doctrees/design.doctree
  doc/build/doctrees/domain.doctree
  doc/build/doctrees/environment.pickle
  doc/build/doctrees/index.doctree
  doc/build/doctrees/infrastructure.doctree
  doc/build/doctrees/introduction.doctree
  doc/build/doctrees/tools.doctree
  doc/build/doctrees/usage.doctree
  doc/build/html/_static/basic.css
  doc/build/html/_static/documentation_options.js
  doc/build/html/_static/searchtools.js
  doc/build/html/application.html
  doc/build/html/design.html
  doc/build/html/domain.html
  doc/build/html/genindex.html
  doc/build/html/index.html
  doc/build/html/infrastructure.html
  doc/build/html/introduction.html
  doc/build/html/objects.inv
  doc/build/html/py-modindex.html
  doc/build/html/search.html
  doc/build/html/searchindex.js
  doc/build/html/tools.html
  doc/build/html/usage.html
  examples/json/create_outlaw.json
  tests/mocks/mock_mail_notifier.py
  tests/mocks/mock_raid_repository.py
  tests/test_end_raid.py
  tests/test_grade_raid.py
  thesheriff/application/outlaw/invite_friend.py
  thesheriff/application/outlaw/send_notification_after_raid.py
  thesheriff/application/raid/end_raid.py
  thesheriff/application/raid/grade_raid.py
  thesheriff/application/raid/request/end_raid_request.py
  thesheriff/configuration.py
  thesheriff/domain/gang/gang.py
  thesheriff/domain/gang/gang_factory.py
  thesheriff/domain/mail/mail.py
  thesheriff/domain/mail/mail_factory.py
  thesheriff/domain/mail/notifier/mail_notifier.py
  thesheriff/domain/outlaw/repository/outlaw_repository.py
  thesheriff/domain/raid/raid_factory.py
  thesheriff/infrastructure/controllers/raid_controller.py
  thesheriff/infrastructure/notifier/smtp_mail_notifier.py
  thesheriff/infrastructure/repository/mysql_raid_repository.py
Labels: CU behavioral validation

#117 Request objects in CUs
  doc/build/doctrees/application.doctree
  doc/build/doctrees/design.doctree
  doc/build/doctrees/domain.doctree
  doc/build/doctrees/environment.pickle
  doc/build/doctrees/index.doctree
  doc/build/doctrees/infrastructure.doctree
  doc/build/doctrees/introduction.doctree
  doc/build/doctrees/tools.doctree
  doc/build/doctrees/usage.doctree
  doc/build/html/_images/the_sheriff_class_diagram1.png
  doc/build/html/application.html
  doc/build/html/infrastructure.html
  doc/build/html/searchindex.js
  doc/diagrams/thesheriff_class_diagram.png
  tests/test_grade_raid.py
  tests/test_list_friends.py
  tests/test_outlaw_list_gangs.py
  tests/test_rate_raid.py
  thesheriff/application/outlaw/invite_friend.py
  thesheriff/application/outlaw/list_friends.py
  thesheriff/application/outlaw/list_gangs.py
  thesheriff/application/outlaw/rate_raid.py
  thesheriff/application/outlaw/request/invite_friend_request.py
  thesheriff/application/outlaw/request/list_friends_request.py
  thesheriff/application/outlaw/request/list_gangs_request.py
  thesheriff/application/raid/grade_raid.py
  thesheriff/application/raid/request/grade_raid_request.py
  thesheriff/application/raid/request/rate_raid_request.py
  thesheriff/domain/mail/mail_factory.py
  thesheriff/infrastructure/controllers/outlaw_controller.py
  thesheriff/infrastructure/controllers/raid_controller.py
Labels: documentation, refactor

#123 JoingGang - Test Case
  tests/test_join_gang.py
Labels: test

#122 Validate invite friend
  doc/build/doctrees/application.doctree
  doc/build/doctrees/environment.pickle
  doc/build/html/_images/thesheriff_class_diagram.png
  doc/build/html/application.html
  tests/test_invite_friend.py
  thesheriff/application/outlaw/invite_friend.py
Labels: CU behavioral validation, refactor, test

#121 documentation format reviewed
  doc/build/doctrees/design.doctree
  doc/build/doctrees/domain.doctree
  doc/build/doctrees/index.doctree
  doc/build/doctrees/infrastructure.doctree
  doc/build/doctrees/introduction.doctree
  doc/build/doctrees/technologies.doctree
  doc/build/doctrees/tools.doctree
  doc/build/doctrees/usage.doctree
  doc/build/html/_sources/application.rst.txt
  doc/build/html/_sources/design.rst.txt
  doc/build/html/_sources/domain.rst.txt
  doc/build/html/_sources/index.rst.txt
  doc/build/html/_sources/infrastructure.rst.txt
  doc/build/html/_sources/introduction.rst.txt
  doc/build/html/_sources/technologies.rst.txt
  doc/build/html/_sources/tools.rst.txt
  doc/build/html/_sources/usage.rst.txt
  doc/build/html/application.html
  doc/build/html/design.html
  doc/build/html/domain.html
  doc/build/html/genindex.html
  doc/build/html/index.html
  doc/build/html/infrastructure.html
  doc/build/html/introduction.html
  doc/build/html/objects.inv
  doc/build/html/py-modindex.html
  doc/build/html/search.html
  doc/build/html/searchindex.js
  doc/build/html/technologies.html
  doc/build/html/tools.html
  doc/build/html/usage.html
  doc/source/_build/html/.buildinfo
  doc/source/_build/html/.doctrees/environment.pickle
  doc/source/_build/html/.doctrees/index.doctree
  doc/source/_build/html/.doctrees/infrastructure.doctree
  doc/source/_build/html/.doctrees/usage.doctree
  doc/source/_build/html/_sources/index.rst.txt
  doc/source/_build/html/_sources/infrastructure.rst.txt
  doc/source/_build/html/_sources/usage.rst.txt
  doc/source/_build/html/genindex.html
  doc/source/_build/html/index.html
  doc/source/_build/html/infrastructure.html
  doc/source/_build/html/objects.inv
  doc/source/_build/html/py-modindex.html
  doc/source/_build/html/search.html
  doc/source/_build/html/searchindex.js
  doc/source/_build/html/usage.html
  doc/source/application.rst
  doc/source/design.rst
  doc/source/domain.rst
  doc/source/index.rst
  doc/source/infrastructure.rst
  doc/source/introduction.rst
  doc/source/technologies.rst
  doc/source/tools.rst
  doc/source/usage.rst
Labels: documentation

#124 fix: sync requirements for readthedocs
  Pipfile.lock
  doc/requirements.txt
Labels: documentation

#127 fix: readme
  README.md
Labels: documentation

#130 Last version of class diagram
  doc/build/doctrees/application.doctree
  doc/build/doctrees/conclusion.doctree
  doc/build/doctrees/design.doctree
  doc/build/doctrees/domain.doctree
  doc/build/doctrees/environment.pickle
  doc/build/doctrees/index.doctree
  doc/build/doctrees/infrastructure.doctree
  doc/build/doctrees/introduction.doctree
  doc/build/doctrees/technologies.doctree
  doc/build/doctrees/usage.doctree
  doc/build/html/_images/thesheriff_class_diagram.png
  doc/build/html/_static/basic.css
  doc/build/html/_static/documentation_options.js
  doc/build/html/_static/searchtools.js
  doc/build/html/application.html
  doc/build/html/conclusion.html
  doc/build/html/design.html
  doc/build/html/domain.html
  doc/build/html/genindex.html
  doc/build/html/index.html
  doc/build/html/infrastructure.html
  doc/build/html/introduction.html
  doc/build/html/objects.inv
  doc/build/html/py-modindex.html
  doc/build/html/search.html
  doc/build/html/searchindex.js
  doc/build/html/technologies.html
  doc/build/html/usage.html
  doc/diagrams/thesheriff_class_diagram.png
  thesheriff/application/raid/create_raid.py
  thesheriff/application/raid/grade_raid.py
  thesheriff/domain/gang/gang.py
  thesheriff/domain/gang/gang_factory.py
Labels: documentation

#131 doc: usage
  doc/build/doctrees/application.doctree
  doc/build/doctrees/conclusion.doctree
  doc/build/doctrees/design.doctree
  doc/build/doctrees/domain.doctree
  doc/build/doctrees/environment.pickle
  doc/build/doctrees/index.doctree
  doc/build/doctrees/infrastructure.doctree
  doc/build/doctrees/introduction.doctree
  doc/build/doctrees/technologies.doctree
  doc/build/doctrees/usage.doctree
  doc/build/html/_sources/usage.rst.txt
  doc/build/html/_static/basic.css
  doc/build/html/_static/documentation_options.js
  doc/build/html/_static/searchtools.js
  doc/build/html/application.html
  doc/build/html/conclusion.html
  doc/build/html/design.html
  doc/build/html/domain.html
  doc/build/html/genindex.html
  doc/build/html/index.html
  doc/build/html/infrastructure.html
  doc/build/html/introduction.html
  doc/build/html/py-modindex.html
  doc/build/html/search.html
  doc/build/html/searchindex.js
  doc/build/html/technologies.html
  doc/build/html/usage.html
  doc/source/_build/html/.doctrees/environment.pickle
  doc/source/_build/html/.doctrees/index.doctree
  doc/source/_build/html/.doctrees/infrastructure.doctree
  doc/source/_build/html/.doctrees/usage.doctree
  doc/source/_build/html/_sources/index.rst.txt
  doc/source/_build/html/_sources/usage.rst.txt
  doc/source/_build/html/_static/basic.css
  doc/source/_build/html/_static/documentation_options.js
  doc/source/_build/html/_static/searchtools.js
  doc/source/_build/html/genindex.html
  doc/source/_build/html/index.html
  doc/source/_build/html/infrastructure.html
  doc/source/_build/html/objects.inv
  doc/source/_build/html/py-modindex.html
  doc/source/_build/html/search.html
  doc/source/_build/html/searchindex.js
  doc/source/_build/html/usage.html
  doc/source/usage.rst
  examples/json/create_outlaw_1.json
  examples/json/create_outlaw_2.json
  examples/json/create_outlaw_3.json
  examples/json/rate_raid_outlaw_2.json
  examples/json/rate_raid_outlaw_3.json
  thesheriff/infrastructure/controllers/outlaw_controller.py
  thesheriff/infrastructure/controllers/raid_controller.py
  thesheriff/infrastructure/repository/mysql_raid_repository.py
Labels: documentation

#134 Conclusion pending things to be done in the future
  doc/source/conclusion.rst
Labels: documentation

#136 feature: validation script
  doc/build/doctrees/environment.pickle
  doc/build/doctrees/usage.doctree
  doc/build/html/_sources/usage.rst.txt
  doc/build/html/searchindex.js
  doc/build/html/usage.html
  doc/source/usage.rst
  validate.sh
Labels: enhancement
